a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alfanúmerico?', a.isalnum())
print('Esta em maiuscula?', a.isupper())
print('Esta em minuscula?', a.islower())
print('Esta Capitalizada?', a.istitle())