algo = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(algo))
print('Só tem espaços? ', algo.isspace())
print('É um número? ', algo.isnumeric())
print('É alfabetico? ', algo.isalpha())
print('É alfanúmerico?', algo.isalnum())
print('Esta em maiuscula?', algo.isupper())
print('Esta em minuscula?', algo.islower())
print('Esta Capitalizada?', algo.istitle())